---
- name: Install GIT
  become: true
  ansible.builtin.package:
    name: git
    state: present
- name: Get lighthouse distrib
  ansible.builtin.git:
    repo: "{{ url_to_lighthouse }}"
    version: master
    dest: "{{ site_path }}"
    accept_hostkey: true
- name: Install the 'Development tools' package group
  become: true
  ansible.builtin.yum:
    name: "@Development tools"
    state: present
- name: Get NGINX version
  ansible.builtin.command: nginx -v
  register: nginx_version_result
  ignore_errors: true
  changed_when: false
- name: Get and Install NGINX
  block:
    - name: Get NGINX distrib
      become: true
      ansible.builtin.get_url:
        url: https://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
        dest: /tmp
        mode: "0644"
    - name: Unpack nginx distrib
      ansible.builtin.unarchive:
        src: /tmp/nginx-{{ nginx_version }}.tar.gz
        dest: /tmp
        remote_src: true
    - name: Configure NGINX
      ansible.builtin.command:
        cmd: ./configure --without-http_rewrite_module --without-http_gzip_module
        chdir: /tmp/nginx-{{ nginx_version }}
    - name: Make NGINX
      ansible.builtin.command:
        cmd: make
        chdir: /tmp/nginx-{{ nginx_version }}
    - name: Install NGINX
      become: true
      ansible.builtin.command:
        cmd: make install
        chdir: /tmp/nginx-{{ nginx_version }}
      notify: Start nginx
    - name: Make NGINX callable
      become: true
      ansible.builtin.command: ln -s /usr/local/nginx/sbin/nginx /usr/bin/nginx
  when:
    - nginx_version_result.failed == true
    - nginx_version not in nginx_version_result.stdout
- name: Configure nginx config for site
  become: true
  ansible.builtin.template:
    src: nginx.cfg.j2
    dest: /usr/local/nginx/conf/nginx.conf
    mode: "0644"
  notify: Restart nginx
- name: Assure that directory conf.d exist
  become: true
  ansible.builtin.file:
    path: /usr/local/nginx/conf/conf.d
    state: directory
    mode: "0644"
- name: Make config for lighthouse
  become: true
  ansible.builtin.template:
    src: default.cfg.j2
    dest: /usr/local/nginx/conf/conf.d/default.conf
    mode: "0644"
  notify: Restart nginx

